name: expenses_manager
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  shared_preferences:
  intl: ^0.19.0
  printing:
  stacked:
  connectivity_plus: ^5.0.2
  event_bus: ^2.0.0
  flutter_launcher_icons:
  fluttertoast:
  date_picker_plus: ^3.0.2
#firebase
  firebase_core: ^2.29.0
  firebase_analytics: ^10.10.1
  cloud_firestore: ^4.16.1

  json_annotation:
  dropdown_button2: ^2.3.9
  lottie:
  mask_text_input_formatter:
  cached_network_image:
  syncfusion_flutter_charts: ^25.1.40
  syncfusion_flutter_pdf: ^25.1.42
  open_file: ^3.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner:


  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img.png"       # flutter pub get
  remove_alpha_ios: true                          # flutter pub run flutter_launcher_icons:main


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/fonts/
    - assets/fonts/open-sans.ttf

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 600

    - family: semibold
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 700

    - family: bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800

    - family: Montserrat
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: extraBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
